name: business
description: The business package.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.2.0

dependencies:
  async_redux: ^21.0.1
  connectivity_plus: ^5.0.2
  fast_immutable_collections: ^9.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^16.3.0
  flutter_timezone: ^1.0.8
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  http_client:
    path: ../http_client
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  models:
    path: ../models
  path_provider: ^2.1.2
  pro_pretty_logging: ^1.0.5
  storage:
    path: ../storage
  uuid: ^4.3.2

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  isar_generator: ^3.1.0
  json_serializable: ^6.7.1
  pro_lints: ^2.0.2
