name: storage
description: The storage package.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.2.0

dependencies:
  hive: ^2.2.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  isar_generator: ^3.1.0
  pro_lints: ^2.0.2
